apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scout
  labels:
    app: scout
spec:
  selector:
    matchLabels:
      app: scout
  template:
    metadata:
      labels:
        app: scout
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - image: josepht96/scout:latest
          imagePullPolicy: Always
          name: scout
          resources: {}
          ports:
            - containerPort: 8080
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
