apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scout
  name: scout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scout
  template:
    metadata:
      labels:
        app: scout
    spec:
      containers:
      - image: josepht96/scout:latest
        imagePullPolicy: Always
        name: scout
        resources: {}
        ports:
        - containerPort: 8080
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName